### ISSUE TITLE
`confint()` may not behave as intended

### ISSUE THREAD

**Issue by tgerke** [stopsack/risks#7]
`risks.Rmd` states 

> *  `confint(fit, level = 0.9)` returns *90%* confidence intervals.

but I'm pretty sure this will only correspond to the delta method confidence intervals (right?). If other types of estimates are in-use, users might want to go to `confint` with caution. Alternatively, we could roll a `confint.risks` for `risks`-type objects that will use the kind of confidence interval that was specified in the model-fitting step.

**Comment by stopsack** [comment]
Great point to double-check, @tgerke!

There should be model-specific `confint()` methods. It would be good to add a test that these are actually getting used on every model type when the user calls `confint()` on the model fit. Or combine in a `confint.risks()` as you suggest.

https://github.com/stopsack/risks/blob/7013446950d60da163f70999d59df95132f6a5bc/R/margstd-utils.R#L323-L410

https://github.com/stopsack/risks/blob/7013446950d60da163f70999d59df95132f6a5bc/R/robpoisson-utils.R#L16-L54

https://github.com/stopsack/risks/blob/7013446950d60da163f70999d59df95132f6a5bc/R/caseduplicate.R#L28-L64

**Comment by stopsack** [comment]
Changed the user-interface to have one `confint.risks()` S3 method that calls the other methods if needed. Now, for consistency, also `confint()`, like `tidy()` and `summary()`, uses Wald-type intervals instead of profile likelihood, when a user selects the alternative estimation approaches `"glm"`, `"glm_startp"`, or `"glm_startd"`.
